### ISSUE TITLE
add support for delegation accounts

### ISSUE THREAD

**Issue by logicminds** [eXamadeus-zz/godaddypy#17]
Awesome library.  Can you add support for delegation accounts.  I control my friends account. 

https://developer.godaddy.com/getstarted

Delegation

You are authenticated as one Shopper, but performing actions on behalf of another. You will need to use the `X-Shopper-Id` header to specify who you're targeting, but must ignore references to Subaccounts.

**Comment by eXamadeus-zz** [comment]
This could be done.  I will file it as an enhancement.  This is a side-project for me, so I generally get most of my work done during the holidays.

If I get some free time over Thanksgiving I'll try to tackle it, otherwise it'll probably be around Christmas time.  That is, unless someone beats me to it 😉

**Comment by claywd** [comment]
Same issue here

**Comment by eXamadeus-zz** [comment]
Sorry I haven't been active lately.  Work and personal life have become "all-encompassing".  I have some free time coming up this month and I will spend some time during those few days looking into this issue.

Thanks for your patience!

**Comment by eXamadeus-zz** [comment]
Added support for delegate accounts.  I have not thoroughly tested this functionality, as I have no delegate accounts myself, but you should be able to target them now with the new delegate parameter on the Account constructor.
